### ISSUE TITLE
Tracking issue for breaking changes in 4.x

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#1860]
Opening this as a place to keep track of what is currently breaking between 3.x (stable branch) and the upcoming 4.x (main branch).

### Planned breaking changes in 4.x
 - [x] modifying app code via broccoli is not going to be supported
 - [x] new index.html location and format required
 - [x] explicit babel config and vite (or webpack) config required
 - [x] strict ES module evaluation order has made some things more eager than before
 - [x] the EMBER_ENV will be controlled via Vite's `--mode` argument.
 - [x] the app is responsible for the config module, content for `'config-module'` code must be moved on the app-side
 - [x] the app is responsible for the app-boot module, content for `'app-boot'` code must be moved on the app-side
 - [x]  `serverMiddleware` hook is not supported.
 - [x] AMD loader will be completely gone
   - [x] todo: remove loader.js from blueprints and app-templates, then remove it from the special `forbiddenVendorPath` (it's fine for people to add it, I just forbid it while testing to ensure nothing in embroider could accidentally use it)
 - [x] the `dependsOnComponents` and `dependsOnModules` compatibility rules exist to force things into the AMD loader, and there won't be an AMD loader, so they need to either be removed or change their API.

### Currently breaking behaviors that we're working on
 - [x] https://github.com/embroider-build/embroider/issues/2287
 - [ ] we skipped tests for `app.import` with custom `outputPath`. We may or may not keep support for this feature.
 - [ ] #1965
 - [ ] webpack support is gone right now, we intend to do an inverted-control version of webpack too.
 - [x] We needed to skip some tests in windows because the build was timing out. We should do some basic analysis why things are running so slowly (or hanging) and see if we can re-enable [these tests](https://github.com/embroider-build/embroider/pull/1801/files#diff-92c202257f283d4d5fd53ed3a23799099f53ce4e5f4109d6a213fc211e00dcf8R32)
 - [ ] we've skipped engines tests and they need to be re-enabled and fixed before release
 - [ ] we've skipped fastboot-app-test and they need to be re-enabled and fixed before release (with possible new way of running fastboot after a vite build)
   - [ ] alternatively, if we can demonstrate native vite SSR working on the basic app template that would create a different upgrade path (in that case, we'd do compatibility to convert fastboot-switching infrastructure to respect vite environment)
 - [x] the new format for the env config doesn't support `!storeConfigInMeta` 

### Things to clean up before release

- [x] `//TODO move the extra forwardslash handling out into the vite plugin`

### Things we may want to break but haven't yet
 - [x] `staticAddonTrees` and `staticAddonTestSupportTrees` set to false was intended as a more-likely-to-work initial adoption mode. But they break things at least as often as they help, because they aggressively pull files into the build that can have problems. People have have a better adoption experience if we always keep them `true` and instead document how to identify when some small number of modules are not found at runtime.

**Comment by mansona** [comment]
> AMD loader will be completely gone

Is this done now? or do you mean the extra work that actually removes the loader?

**Comment by ef4** [comment]
I mean we should finish landing https://github.com/embroider-build/embroider/pull/2103, and then ensure that loader.js is not in `/@embroider/core/vendor.js`.

In whole apps I've been testing under vite there's *nothing* in the AMD loader anyway.

**Comment by bwbuchanan** [comment]
How is route-splitting intended to work with ember-resolver explicit modules? I've been experimenting with using the `vite` blueprint in one of my apps, and after updating to the latest everything from this week, most of my routes stopped working. After some hours of debugging, it appears that the cause was making this change in app.ts:

```
  override Resolver = Resolver.withModules(compatModules);
```

Because `@embroider/virtual/compat-modules` doesn't get updated when lazy-loaded routes are loaded, the resolver never finds them.

**Comment by ef4** [comment]
Ah, good catch. We must lack tests for that combination of settings.

**Comment by ef4** [comment]
The route splitting should be fixed on main now..
