### ISSUE TITLE
Provide a new way to load initialisers that doesn't use require.entries

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1961]
In https://github.com/embroider-build/embroider/pull/1780 there was an attempt to fix the timing issues around loading initialisers but it wouldn't guarantee that things would happen with the right timing. 

Also we should not be using the `ember-load-initializers` package because it 100% relies on require.entries (which we should not be baking into the modern app boot process).

## Tasks to get this done

- [x] move the app boot out of the entrypoint file https://github.com/embroider-build/embroider/issues/1960
- [x] convert the entrypoint to export an object of modules that are defined from the outside (like the implicit modules implementation)
- [x] implement a new `loadInitialisers()` function that will take named initialisers from the "entrypoint" exported modules and set them up correctly

**Comment by BlueCutOfficial** [comment]
It turns out the last task...

> implement a new loadInitialisers() function that will take named initialisers from the "entrypoint" exported modules and set them up correctly

... was not necessary to support initializers. Nonetheless, a PR has been opened as getting rid of `require` is still relevant on the long run: [ember-cli/ember-load-initializers#305](https://github.com/ember-cli/ember-load-initializers/pull/305)
