### ISSUE TITLE
Re-implement watch-mode for vite and make sure that we add the tests back in

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#1965]
we skipped the watch-mode tests because they need to change structure and it would be better to do that after we've turned off app rewriting. Specific additional things that need to go into those watch tests, because their coverage got dropped from stage2 tests as they no longer live in stage 2

## TODO - make sure these work

- [ ] changes in app.css are propagated at rebuild
- [ ] public assets are included
- [ ] updated public asset
- [ ] added public asset
- [ ] removed public asset

**Comment by ef4** [comment]
We think we have good enough interactive watch mode tests now.
