### ISSUE TITLE
Remaining issues before we cut the first alpha of Embroider@4

### ISSUE THREAD

**Issue by mansona** [embroider-build/embroider#2207]
While https://github.com/embroider-build/embroider/issues/1860 is a tracking issue for the next Stable release from the main branch, we discussed the changes that we would like to see on main before we cut the first alpha release. This will effectively allow us to give some semver functionality to people using the new blueprint (with obvious alpha caveats before it is actually stable 😂 ) 

## Todo

- [x] Update the implementation for ember-cli-build to match what is now said in the RFC https://github.com/NullVoxPopuli/rfcs/blob/v2-app-spec/text/0977-v2-app-format.md#ember-pre-build-config---ember-cli-buildjs
- [x] implement setting `staticInvokables` that is a combination of `staticComponents`, `staticModifiers`, and `staticHelpers`
  - [x] implement this on stable with a deprecation
  - [x] Throw an error on main https://github.com/embroider-build/embroider/pull/2246
- [x] throw an error if anyone sets the `skipBabel` setting https://github.com/embroider-build/embroider/pull/2247
- [x] throw an error if anyone sets `staticAddonTrees` or `staticAddonTestSupportTrees` https://github.com/embroider-build/embroider/pull/2256
  - [ ]  optionally document how people would workaround this issue by manually putting things in the requirejs loader
  - [x] implement on stable with a deprecation https://github.com/embroider-build/embroider/pull/2244
- [x] stop nullifying the loader.js library so people can use it if they want to (even if we don't) - https://github.com/embroider-build/embroider/pull/2242
- [x] throw an error if anyone sets `staticEmberSource` to false https://github.com/embroider-build/embroider/pull/2255
  - [x] implement on stable with a deprecation https://github.com/embroider-build/embroider/pull/2245
- [x] ensure the simplified `ember()` and `classicEmberSupport()` vite plugins allow the appropriate level of overriding their results. Right now it doesn't appear possible to unset things like the rollup build options. https://github.com/embroider-build/embroider/pull/2260
- [x] configure release plan to publish the alpha correctly https://github.com/embroider-build/embroider/pull/2259

**Comment by mansona** [comment]
Alpha is out 💪
