### ISSUE TITLE
V2 package RFCs checklist

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#268]
Published RFCs:

 - **proposed**: v2 addon format base spec (https://github.com/emberjs/rfcs/pull/507)

TODO list of additional features that need to get specified in follow RFCs:

 - providing dev middleware
 - providing commands and blueprints
 - preprocessing your parent package's code
 - modifying your parent package's babel config
 - injecting content into index.html (contentFor)
 - accessing the app's configured browser targets from an addon's build file

**Comment by NullVoxPopuli** [comment]
Should we re-purpose this ticket as a quest issue for when V2 addons are "production ready"?

- [ ] Add tests for `@embroider/addon-dev`
- [ ] https://github.com/embroider-build/embroider/issues/1121
  - [ ] https://github.com/embroider-build/embroider/pull/1126
- [ ] https://github.com/embroider-build/embroider/pull/1099
- [ ] Iterate on https://github.com/embroider-build/addon-blueprint
  - [ ] TypeScript?
  - [ ] Interactive? (Monorepo layout, etc (at the time of writing this generates a different structure from the addon-migrator))
- [ ] Iterate on https://github.com/NullVoxPopuli/ember-addon-migrator
  - [ ] Figure out if porting every little detail is worth it, or if replacing is needed in same cases? Can aspects of little details, such as CI config, be transformed?
