### ISSUE TITLE
Stabilization tracking issue

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#501]
TODO list of the high-priority things that will get embroider stabilized and into ember's recommended stack:

 -[ ] add embroider to default addon blueprint's ember-try config
 -[ ] glimmer-vm issues to support optimize-able addons, see https://github.com/embroider-build/embroider/issues/487
 -[ ]ship a stable 1.0 of @embroider/macros (and probably rename it to @ember/macros)
   - docs site
   - finish the work on the env-macros branch (this adds support for some things like `isTesting` and `isDevelopingApp` macros)
   - make sure the HBS macros are up to date with the JS macros
 - [ ] create / test / ship the compatibility shim
   - make ember-auto-import aware of v2 addons. It is our key polyfill for v2 behavior in a v1 world.
 - [ ]complete first version of addon-author-guide
   - have a place for recipes / common issues / etc
   - itemize the different options for authoring format (we expect this to be
     more fluid right now, and move toward standardization after there's real
     feedback)
 - [ ] figure out the plan for including embroider into ember-cli official releases
   - depends on what the ember-cli team is thinking about their overall architecture
   - we could be a direct dependency of ember-cli, or remain an explicitly imported thing from ember-cli-build.js.
